https://docs.julialang.org/en/v1/base/arrays/



https://docs.julialang.org/en/v1/manual/arrays/



https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/



https://cheatsheets.quantecon.org/julia-cheatsheet.html


https://cheatsheets.quantecon.org/


https://www.softcover.io/read/7b8eb7d0/juliabook/basics

https://www.geeksforgeeks.org/arrays-in-julia/

# Introduction to Array

---

Compared to Python, array operations in Julia is in standard library. Hence no need to use any external third party library. One more difference between arrays in Julia and arrays in Numpy is that, arrays in Julia are column oriented while in Numpy they are row oriented.

In this lecture, we will talk about creating array with certain data types, manipulating array, selecting
elements from arrays, as well as how to use its statistical and mathematical capabilities.


### Lecture outline

---

* Scalar, Vector, Matrix, and N dimensional Array


* Shape, Size, Dimension of matrices, and type of entries


* Indexing and Slicing


* Boolean Indexing


* Element-wise Functions


* Statistical Functions


* Linear Algebra

In [79]:
using LinearAlgebra
using SparseArrays

## Scalar, Vector, Matrix, NdArray or Tensor

![alt text](images/scalar-vector-matrix-tensor.png "Title")

In [1]:
# Scalar

scalar = 5

scalar

5

In [7]:
flat_array = [1, 2, 3, 4, 5]

flat_array

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [8]:
# Row vector: size (1, n)

row_vector = [1 2 3 4 5]

row_vector

1×5 Array{Int64,2}:
 1  2  3  4  5

In [11]:
# Column vector: size (n, 1)

column_vector = [1 2 3 4 5]'

column_vector

5×1 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1
 2
 3
 4
 5

In [12]:
# 1d array: size (n, )

arr = [1; 2; 3; 4; 5]

arr

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [18]:
# Matrix - 2D array: size(n, m)

matrix = [1 2 3;
          4 5 6;
          7 8 9]

matrix

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

#### Tensor

![alt text](images/tensor.png "Title")

In [56]:
cat(reshape(0:11, 3, 4)', reshape(12:23, 3, 4)', reshape(24:35, 3, 4)', dims=3)

4×3×3 Array{Int64,3}:
[:, :, 1] =
 0   1   2
 3   4   5
 6   7   8
 9  10  11

[:, :, 2] =
 12  13  14
 15  16  17
 18  19  20
 21  22  23

[:, :, 3] =
 24  25  26
 27  28  29
 30  31  32
 33  34  35

### Different types of matrices

Julia have functions which can generate different matrices.

In [59]:
# Matrix of ones

ones(3, 3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [60]:
# Matrix of zeros

zeros(3, 3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [78]:
# Identity matrix

Matrix(I, 3, 3)

3×3 Array{Bool,2}:
 1  0  0
 0  1  0
 0  0  1

In [80]:
# Diagonal matrix

Diagonal([1, 2, 3])

3×3 Diagonal{Int64,Array{Int64,1}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

There exists `Sparse Matrices`, where most of the values are zeros and few of them are non-zero. If we represent sparse matrices in a usual way it will take huge amount of memory. Hence, it's better to represent them in a compact way. That's where the notion sparse matrix comes in.

In [87]:


sparse(Matrix(I, 3, 3))

3×3 SparseMatrixCSC{Bool,Int64} with 3 stored entries:
  [1, 1]  =  1
  [2, 2]  =  1
  [3, 3]  =  1

## Shape, Size, Dimension of matrices, and type of entries

In [93]:
matrix

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [94]:
# Number of rows and columns

size(matrix)

(3, 3)

In [96]:
# Number of elements (rows * columns)

length(matrix)

9

In [95]:
# Number of dimensions (axis)

ndims(matrix)

2

In [97]:
# Check the type of entries

eltype(matrix)

Int64

### Numpy `arange` and `linspace`

---

They are used to generate sequence of numbers in some range

![alt text](images/arange.png "Title")

In [19]:
np.arange(start=30, stop=40, step=1) # upper boundary is not included

array([30. , 30.2, 30.4, 30.6, 30.8, 31. , 31.2, 31.4, 31.6, 31.8, 32. ,
       32.2, 32.4, 32.6, 32.8, 33. , 33.2, 33.4, 33.6, 33.8, 34. , 34.2,
       34.4, 34.6, 34.8, 35. , 35.2, 35.4, 35.6, 35.8, 36. , 36.2, 36.4,
       36.6, 36.8, 37. , 37.2, 37.4, 37.6, 37.8, 38. , 38.2, 38.4, 38.6,
       38.8, 39. , 39.2, 39.4, 39.6, 39.8])

In [21]:
np.linspace(start=30, stop=40, num=15) # upper boundary is included

array([30.        , 30.71428571, 31.42857143, 32.14285714, 32.85714286,
       33.57142857, 34.28571429, 35.        , 35.71428571, 36.42857143,
       37.14285714, 37.85714286, 38.57142857, 39.28571429, 40.        ])

## Indexing and Slicing

---

Indexing, slicing and iterating are extremely important for data manipulation and analysis because these techinques allow us to select data based on conditions, and copy or update data. Slicing is a way to create a sub-array based on the original array.

In [110]:
# Indexing for vector

row_vector = [5 15 20 25 30 35]

row_vector[1]

row_vector[3:end]

row_vector[2:5]

4-element Array{Int64,1}:
 15
 20
 25
 30

**Indexing for matrices is slightly different compared to vector because we have axis there and we have to figure out which axis do we need. In multidimensional arrays, the first argument is for selecting rows, and the second argument is for selecting columns.**

In [116]:
matrix

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [125]:
# Indexing for matrices


matrix[1, 1] # Select first element

matrix[:, 1] # Select first column vector

matrix[:2, :] # Select second row and all columns of a matrix

matrix[:, 1:2] # Select all rows and first two columns

matrix[:] # Convert matrix to a vector

9-element Array{Int64,1}:
 1
 4
 7
 2
 5
 8
 3
 6
 9

## Boolean Indexing

---

Boolean indexing allows us to select arbitrary elements based on conditions. For example, if we want to find elements that are greater than 5 in a matrix we set up a conditon and it returns boolean values

In [126]:
matrix

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [128]:
matrix .> 5

3×3 BitArray{2}:
 0  0  0
 0  0  1
 1  1  1

In [129]:
matrix[matrix .> 5]

4-element Array{Int64,1}:
 7
 8
 6
 9

In [130]:
# Tilde is the negation operator. It converts True to False and False to True

matrix[.!(matrix .> 5)]

5-element Array{Int64,1}:
 1
 4
 2
 5
 3

We can combine several conditions by using boolean arithmetic operators such as & (and) and | (or)

In [133]:
(matrix .> 3) .& (matrix .< 7)

3×3 BitArray{2}:
 0  0  0
 1  1  1
 0  0  0

In [134]:
matrix[(matrix .> 3) .& (matrix .< 7)]

3-element Array{Int64,1}:
 4
 5
 6

## Arithmetic Operations On Array

---

We can do many things on arrays, such as mathematical manipulation such as addition, subtraction, square, exponents. These operators on array apply elementwise.

In [135]:
a = [10, 20, 30, 40, 50]

b = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [147]:
a - b

a + b

a ./ b

a .* b

a .^ b

5-element Array{Int64,1}:
        10
       400
     27000
   2560000
 312500000

## Element-Wise Array Functions

In [150]:
arr = [4, 8, 16, 20, 25]


arr

5-element Array{Int64,1}:
  4
  8
 16
 20
 25

In [154]:
sqrt.(arr) # Square root of array values

exp.(arr) # Exponent of array values

log.(arr) # Natural logarithm of array values

5-element Array{Float64,1}:
 1.3862943611198906
 2.0794415416798357
 2.772588722239781
 2.995732273553991
 3.2188758248682006

## Statistical Methods

In [157]:
matrix

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [159]:
maximum(matrix) # Maximum element in matrix

minimum(matrix) # Minimum element in matrix

1

Ofter, we need to know the maximum and minimum value along an axis.

In [169]:
findmax(matrix, dims=1) # Along x axis

findmax(matrix, dims=2) # Along y axis

([3; 6; 9], CartesianIndex{2}[CartesianIndex(1, 3); CartesianIndex(2, 3); CartesianIndex(3, 3)])

We can calculate sum and cumulative sum of array elements

In [183]:
sum(matrix) # Sum of the elements

sum(matrix, dims=1) # Sum along x axis

sum(matrix, dims=2) # Sum along y axis

cumsum(matrix, dims=1) # Cumulative sum along x axis

cumsum(matrix, dims=2) # Cumulative sum along y axis

3×3 Array{Int64,2}:
 1   3   6
 4   9  15
 7  15  24

# ზემოთ კარგი ყველაფერი

## Linear Algebra

---

Numpy is highly optimized for linear algebra operations. These are operations defined mostly on matrices and may differ from conventional operations. For example multiplication operations is different in case of matrices then for just two numbers.

In [55]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# Transposing a matrix means to exchange rows and columns

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
# star (*) operator performs elementwise multiplications between matrices

matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [58]:
# To have proper matrix multiplication we have to use .dot() method or @ sign

np.dot(matrix, matrix)

matrix @ matrix

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [60]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# Diagonal elements of a matrix

np.diag(matrix)

array([1, 5, 9])

In [61]:
# Find the trace of a matrix - Trace is the sum of the main diagonal elements

np.trace(matrix)

15

NumPy has dedicated sub-package or sub-library for linear algebra operations. We can see few of them.

In [62]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# Find the determinant of a matrix

np.linalg.det(matrix)

-9.51619735392994e-16

In [ ]:
# Find the inverse of a matrix

np.linalg.inv(matrix)

# Summary

---

This lecture has to be a strong foundation of towards more advanced Pandas as Pandas is built on top of NumPy and many of the functions and capabilities of NumPy are available to you within Pandas.